create user C##CLIENT IDENTIFIED by 12345678;
GRANT CREATE SESSION,CONNEC TO  C##CLIENT;
GRANT 
SELECT ANY TABLE,
INSERT ANY TABLE,
UPDATE ANY TABLE,
DELETE ANY TABLE TO  C##CLIENT;
         GRANT EXECUTE ON C##SUPER.OBS_PACK TO C##CLIENT;
         GRANT EXECUTE ON C##SUPER.USER_PACK TO C##CLIENT;
     COMMIT;
     
create user C##MANAGER IDENTIFIED by Admin12345;
GRANT CREATE SESSION,CONNECT  TO  C##MANAGER;
GRANT 
SELECT ANY TABLE,
INSERT ANY TABLE,
UPDATE ANY TABLE,
DELETE ANY TABLE TO  C##MANAGER;
GRANT EXECUTE ON C##SUPER.OBS_PACK TO C##MANAGER;
GRANT EXECUTE ON C##SUPER.ADMIN_PACK TO C##MANAGER;
GRANT EXECUTE ON C##SUPER.xml_PACKAGE TO C##MANAGER;
  COMMIT;
  
  CREATE USER C##SUPER IDENTIFIED BY SYSTEM12345;
  GRANT ALL PRIVILEGES TO C##SUPER;
  
  
CREATE TABLESPACE my_data
  DATAFILE 'C:\DB\DATA.pdb'
  SIZE 500M
  AUTOEXTEND ON NEXT 50M
  MAXSIZE 2048M;
  
  ALTER USER  C##MANAGER DEFAULT TABLESPACE my_data;
     ALTER USER  C##CLIENT DEFAULT TABLESPACE my_data;
     ALTER USER  C##SUPER DEFAULT TABLESPACE my_data;