CREATE OR REPLACE DIRECTORY PIC_DIR AS 'C:/APP/';
create or replace Procedure ADD_PICTURE --добавление картинки 
(PICTURE IN VARCHAR2,ID_CAR IN INT, ID_SPARES IN INT )
IS 
 ID_PICTURE INT;
 L_BLOB BLOB;
 L_BFILE BFILE;
 BEGIN 
SELECT PICTURE_S.NEXTVAL INTO ID_PICTURE  FROM dual;
 INSERT INTO PICTURES
 ( ID_PICTURE,ID_CAR, ID_SPARE,PICTURE)
 VALUES
 (ID_PICTURE,ID_CAR,ID_SPARES,EMPTY_BLOB())
 RETURN PICTURE INTO L_BLOB;
 
 L_BFILE := BFILENAME('PIC_DIR',PICTURE);
 DBMS_LOB.FILEOPEN(L_BFILE,DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(L_BLOB,L_BFILE, DBMS_LOB.GETLENGTH(L_BFILE));
   DBMS_LOB.FILECLOSE(L_BFILE);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;

CONNECT C##CLIENT/12345678;
BEGIN C##SUPER.USER_PACK.ADD_PICTURE('IMG_0402.jpg',NULL,NULL);END;
SELECT * FROM PICTURES;