CREATE OR REPLACE PACKAGE USER_PACK AS
 PROCEDURE ADD_PICTURE(PICTURE IN VARCHAR2,ID_CAR IN INT, ID_SPARES IN INT );
 Procedure ADD_CAR --доьавление нового авто
(ID_USER IN INT, DESCRIPTION_CAR IN VARCHAR2,PRICE IN INT, MODEL1  IN VARCHAR2, ID_PIC INT DEFAULT 0);
Procedure ADD_COMMENT --добавление нового комента
(ID_USER IN INT, COMMENT1 IN VARCHAR2, ID_CAR1 IN INT,ID_SPARE1 IN INT );
 Procedure ADD_SAVED --добавление в изыбранное 
(ID_USER IN INT, ID_CAR IN  INT,ID_SPARE IN INT,DATE1 IN DATE);
Procedure ADD_SPARES --добавление запчасти
(ID_USER IN INT, SPARES IN VARCHAR2,PRICE IN INT, MODEL1  IN VARCHAR2, ID_PIC INT DEFAULT 0);
Procedure ADD_USER --добавление нового юзера\регистрация
 (LOGIN IN VARCHAR2,PASSWORD IN VARCHAR2,NAME IN VARCHAR2);
PROCEDURE UPDATE_CAR
(DES IN VARCHAR2,NEWPRICE IN INT, IC IN INT );
 Procedure UPDATE_SPARES
(DES IN VARCHAR2,NEWPRICE IN INT, IDS IN INT );
 Procedure ADD_CONTACT--добавление контактов
 (CONTACT IN VARCHAR2,ID_USER IN VARCHAR2);
  Procedure USER_SAVED
 (ID_USER1 IN INT);
END USER_PACK;
-------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY USER_PACK  AS
Procedure ADD_PICTURE --добавление картинки 
(PICTURE IN VARCHAR2,ID_CAR IN INT, ID_SPARES IN INT )
IS 
 ID_PICTURE INT;
 L_BLOB BLOB;
 L_BFILE BFILE;
 BEGIN 
SELECT PICTURE_S.NEXTVAL INTO ID_PICTURE  FROM dual;
 INSERT INTO PICTURES
 ( ID_PICTURE,ID_CAR, ID_SPARE,PICTURE)
 VALUES
 (ID_PICTURE,ID_CAR,ID_SPARES,EMPTY_BLOB())
 RETURN PICTURE INTO L_BLOB;
 L_BFILE := BFILENAME('PIC_DIR',PICTURE);
 DBMS_LOB.FILEOPEN(L_BFILE,DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(L_BLOB,L_BFILE, DBMS_LOB.GETLENGTH(L_BFILE));
   DBMS_LOB.FILECLOSE(L_BFILE);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_CAR --доьавление нового авто
(ID_USER IN INT, DESCRIPTION_CAR IN VARCHAR2,PRICE IN INT, MODEL1  IN VARCHAR2, ID_PIC INT DEFAULT 0)
 IS 
 ID_CAR INT;
 ID_MODEL1 INT;
 BEGIN 
 SELECT CAR_S.NEXTVAL INTO ID_CAR  FROM dual;
 SELECT ID_MODEL INTO ID_MODEL1 FROM MODEL_ WHERE MODEL_.MODEL_ LIKE UPPER(MODEL1);
 INSERT INTO CAR
 ( ID_CAR, ID_USER,ID_MODEL,ID_PIC,DESCRIPTION_CAR,PRICE)
 VALUES
 (ID_CAR,ID_USER,ID_MODEL1,ID_PIC,description_car,PRICE);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_COMMENT --добавление нового комента
(ID_USER IN INT, COMMENT1 IN VARCHAR2, ID_CAR1 IN INT,ID_SPARE1 IN INT )
 IS 
 ID_COMMENT INT;
 BEGIN 
 SELECT COMMENT_S.NEXTVAL INTO ID_COMMENT  FROM dual;
 INSERT INTO COMMENT_
 ( ID_COMMENT, ID_USER,ID_CAR,ID_SPARE,COMMENT_)
 VALUES
 (ID_COMMENT,ID_USER,ID_CAR1,ID_SPARE1,COMMENT1);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_CONTACT--добавление контактов
 (CONTACT IN VARCHAR2,ID_USER IN VARCHAR2)
 IS 
 ID_CONTACT INT;
 BEGIN 
 SELECT CONTACT_S.NEXTVAL INTO ID_CONTACT  FROM dual;
 INSERT INTO CONTACTS
 ( ID_CONTACTS, CONTACT, ID_USER)
 VALUES
 (ID_CONTACT,CONTACT,ID_USER);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_SAVED --добавление в изыбранное 
(ID_USER IN INT, ID_CAR IN  INT,ID_SPARE IN INT,DATE1 IN DATE)
 IS 
 ID_SAVED INT;
 BEGIN 
 SELECT SAVED_S.NEXTVAL INTO ID_SAVED  FROM dual;
 INSERT INTO SAVED
 ( ID_SAVED, ID_USER,ID_CAR,ID_SPARE, DATE_)
 VALUES
 (ID_SAVED,ID_USER,ID_CAR,ID_SPARE,DATE1);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_SPARES --добавление запчасти
(ID_USER IN INT, SPARES IN VARCHAR2,PRICE IN INT, MODEL1  IN VARCHAR2, ID_PIC INT DEFAULT 0)
 IS 
 ID_SPARES INT;
 ID_MODEL1 INT;
 BEGIN 
 SELECT SPARE_S.NEXTVAL INTO ID_SPARES  FROM dual;
 SELECT ID_MODEL INTO ID_MODEL1 FROM MODEL_ WHERE MODEL_.MODEL_ LIKE UPPER(MODEL1);
 INSERT INTO SPARES
 ( ID_SPARES, ID_USER,ID_MODEL,ID_PIC,SPARES,PRICE)
 VALUES
 (ID_SPARES,ID_USER,ID_MODEL1,ID_PIC,SPARES,PRICE);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_USER --добавление нового юзера\регистрация
 (LOGIN IN VARCHAR2,PASSWORD IN VARCHAR2,NAME IN VARCHAR2)
 IS 
 ID_USER INT;
 BEGIN 
 SELECT USER_S.NEXTVAL INTO ID_USER  FROM dual;
 INSERT INTO Users_
 ( ID_USER, LOGIN, PASSWORD,NAME,PRIVILEGE_)
 VALUES
 (ID_USER,LOGIN,PASSWORD,NAME,'USER');
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
 Procedure UPDATE_CAR
(DES IN VARCHAR2,NEWPRICE IN INT, IC IN INT )
IS 
 BEGIN 
 IF DES IS NULL THEN
 UPDATE CAR 
 SET PRICE=NEWPRICE WHERE ID_CAR =IC;
 ELSIF DES IS NULL THEN
 UPDATE CAR 
 SET DESCRIPTION_CAR=DES WHERE ID_CAR =IC;
 ELSE
  UPDATE CAR 
 SET DESCRIPTION_CAR=DES,PRICE =NEWPRICE WHERE ID_CAR =IC;
 END IF;
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
 Procedure UPDATE_SPARES
(DES IN VARCHAR2,NEWPRICE IN INT, IDS IN INT )
IS 
 BEGIN 
 IF DES IS NULL THEN
 UPDATE SPARES 
 SET PRICE=NEWPRICE WHERE ID_SPARES =IDS;
 ELSIF DES IS NULL THEN
 UPDATE SPARES 
 SET SPARES=DES WHERE ID_SPARES =IDS;
 ELSE
  UPDATE SPARES 
 SET SPARES=DES,PRICE =NEWPRICE WHERE ID_SPARES =IDS;
 END IF;
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure USER_SAVED
(ID_USER1 IN INT)
 IS
CURSOR GET_CAR IS
       SELECT ID_CAR FROM saved WHERE ID_USER = ID_USER1;
  U GET_CAR%ROWTYPE; 
BEGIN
BEGIN
OPEN GET_CAR;
LOOP  
EXIT WHEN GET_CAR%NOTFOUND;
     FETCH GET_CAR INTO U;
     IF GET_CAR%FOUND THEN
CAR_BY_ID(U.ID_CAR);
END IF;
END LOOP;
CLOSE GET_CAR;
END;
EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
END USER_PACK;

--CONNECT C##CLIENT/12345678;
--BEGIN C##SUPER.USER_PACK.ADD_POST(1,NULL,NULL,NULL);END;
--DROP PACKAGE USER_PACK;
CREATE OR REPLACE PACKAGE ADMIN_PACK AS
 Procedure ADD_BRAND -- добавление нового бренда
 (BRAND IN VARCHAR2);
 Procedure ADD_MODEL --добавление новой модели
 (MODEL_ IN VARCHAR2, BRAND1 IN BRAND.BRAND%TYPE);
 Procedure ADD_POST --добавление нового сообщения от админа
(ID_USER IN INT, ID_AUTO IN  INT,ID_SPARES IN INT, POST IN VARCHAR2);
END ADMIN_PACK;

CREATE OR REPLACE PACKAGE BODY ADMIN_PACK AS
Procedure ADD_MODEL --добавление новой модели
 (MODEL_ IN VARCHAR2, BRAND1 IN BRAND.BRAND%TYPE)
 IS 
 ID_MODEL INT;
 ID_BRAND INT;
 BEGIN 
 SELECT MODEL_S.NEXTVAL INTO ID_MODEL  FROM dual;
 SELECT ID_BRAND INTO ID_BRAND FROM BRAND WHERE BRAND like UPPER(BRAND1);
 INSERT INTO MODEL_
 ( ID_MODEL, MODEL_,ID_BRAND)
 VALUES
 (ID_MODEL,UPPER(MODEL_),ID_BRAND);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_POST --добавление нового сообщения от админа
(ID_USER IN INT, ID_AUTO IN  INT,ID_SPARES IN INT, POST IN VARCHAR2)
 IS 
 ID_POST INT;
 BEGIN 
 SELECT POST_S.NEXTVAL INTO ID_POST  FROM dual;
 INSERT INTO POST
 ( ID_POST, ID_USER,ID_AUTO,ID_SPARES,POST)
 VALUES
 (ID_POST,ID_USER,ID_AUTO,ID_SPARES,POST);
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
Procedure ADD_BRAND -- добавление нового бренда
 (BRAND IN VARCHAR2)
 IS 
 ID_BRAND INT;
 BEGIN 
 SELECT BRAND_S.NEXTVAL INTO ID_BRAND  FROM dual;
 INSERT INTO BRAND
 ( ID_BRAND, BRAND)
 VALUES
 (ID_BRAND,UPPER(BRAND));
 COMMIT;
 EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END;
END ADMIN_PACK;