CREATE OR REPLACE TRIGGER TR_ADD_LOGIN
BEFORE INSERT ON  USERS_
	FOR EACH ROW
    DECLARE
    A1 INT;
    BEGIN
  SELECT COUNT(*) INTO A1 FROM   USERS_ WHERE LOGIN=:NEW.LOGIN;
  IF A1 !=0 THEN
   raise_application_error(-20001,'Совпадает логин!');
 END IF;
 end;
