 CONNECT C##MANAGER/Admin12345;
BEGIN
ADD_BRAND('ACURA');
ADD_BRAND('Alfa Romeo');
ADD_BRAND('Aston Martin');
ADD_BRAND('Audi');
ADD_BRAND('Bentley');
ADD_BRAND('BMW');
ADD_BRAND('Cadillac');
ADD_BRAND('Changan');
ADD_BRAND('Chery');
ADD_BRAND('Chevrolet');
ADD_BRAND('Chrysler');
ADD_BRAND('Citroen');
ADD_BRAND('DOGE');
ADD_BRAND('FIATE');
ADD_BRAND('FORD');
ADD_BRAND('GELLY');
ADD_BRAND('HAFEI');
ADD_BRAND('HAIMA');
ADD_BRAND('HAVAL');
ADD_BRAND('HONDA');
ADD_BRAND('HUMMER');
ADD_BRAND('HYUNDAI');
ADD_BRAND('INFINITY');
ADD_BRAND('JAGUAR');
ADD_BRAND('JEEP');
ADD_BRAND('KIA');
ADD_BRAND('LADA');
ADD_BRAND('LANCIA');
ADD_BRAND('LAND ROVER');
ADD_BRAND('LEXUS');
ADD_BRAND('LIFAN');
ADD_BRAND('LINCOLN');
ADD_BRAND('MASERATI');
ADD_BRAND('MAZDA');
ADD_BRAND('MERCEDES-BENZ');
ADD_BRAND('MITSUBISHI');
ADD_BRAND('NISSAN');
ADD_BRAND('OLDSMOBILE');
ADD_BRAND('OPEL');
ADD_BRAND('PEOGEOT');
ADD_BRAND('PORSCHE');
ADD_BRAND('RAVON');
ADD_BRAND('RENAULT');
ADD_BRAND('ROVER');
ADD_BRAND('SAAB');
ADD_BRAND('SAIPA');
ADD_BRAND('SANTANA');
ADD_BRAND('SEAT');
ADD_BRAND('SKODA');
ADD_BRAND('SMART');
ADD_BRAND('SUBARU');
ADD_BRAND('SUZUKI');
ADD_BRAND('TATA');
ADD_BRAND('TESLA');
ADD_BRAND('TOYOTA');
ADD_BRAND('VOLKSWAGEN');
ADD_BRAND('VOLVO');
ADD_BRAND('VORTEX');
ADD_BRAND('√¿«');
ADD_BRAND('«¿«');
ADD_BRAND('ÃŒ— ¬»◊');
ADD_BRAND('”¿«');
ADD_BRAND('› — Àﬁ«»¬');
END;
SELECT * FROM MODEL_;
--DELETE FROM BRAND
--WHERE ID_BRAND = 8;

BEGIN
ADD_MODEL('cdx','ACURA%');
ADD_MODEL('NSX','ACURA%');
ADD_MODEL('RLx','ACURA%');
ADD_MODEL('MDX','ACURA%');
ADD_MODEL('RDX','ACURA%');
ADD_MODEL('TLX','ACURA%');
ADD_MODEL('GT','Alfa Romeo%');
ADD_MODEL('MITO','Alfa Romeo%');
ADD_MODEL('SPIDER','Alfa Romeo%');
ADD_MODEL('STEALVIO','Alfa Romeo%');
ADD_MODEL('Giulietta','Alfa Romeo%');
ADD_MODEL('Lagonda','Aston Martin%');
ADD_MODEL('DB11','Aston Martin%');
ADD_MODEL('DB9','Aston Martin%');
ADD_MODEL('DBS','Aston Martin%');
ADD_MODEL('DBX','Aston Martin%');
ADD_MODEL('A3 Sedan','Audi%');
ADD_MODEL('A3','Audi%');
ADD_MODEL('A4','Audi%');
ADD_MODEL('A5','Audi%');
ADD_MODEL('A5 Sportback','Audi%');
ADD_MODEL('A8','Audi%');
ADD_MODEL('e-tron','Audi%');
ADD_MODEL('Q3','Audi%');
ADD_MODEL('Q5','Audi%');
ADD_MODEL('Q8','Audi%');
ADD_MODEL('ArnageT','Bentley%');
ADD_MODEL('Continental GT','Bentley%');
ADD_MODEL('Continental Supersports','Bentley%');
ADD_MODEL('Flying Spur','Bentley%');
ADD_MODEL('Continental Flying Spur','Bentley%');
ADD_MODEL('X1','BMW%');
ADD_MODEL('X2','BMW%');
ADD_MODEL('X3','BMW%');
ADD_MODEL('X3 M','BMW%');
ADD_MODEL('X4','BMW%');
ADD_MODEL('X4 M','BMW%');
ADD_MODEL('X5','BMW%');
ADD_MODEL('X5 M','BMW%');
ADD_MODEL('X6','BMW%');
ADD_MODEL('X6 M','BMW%');
ADD_MODEL('X7','BMW%');
ADD_MODEL('Z4','BMW%');
ADD_MODEL('DTS','Cadillac%');
ADD_MODEL('ELR','Cadillac%');
ADD_MODEL('Escalade','Cadillac%');
ADD_MODEL('STS','Cadillac%');
ADD_MODEL('XT6','Cadillac%');
ADD_MODEL('BLS','Cadillac%');
ADD_MODEL('CS55','Changan%');
ADD_MODEL('CS75','Changan%');
ADD_MODEL('CS35','Changan%');
ADD_MODEL('Raeton','Changan%');
ADD_MODEL('Eado','Changan%');
ADD_MODEL('Hunter','Changan%');
ADD_MODEL('Amulet','Chery%');
ADD_MODEL('Fora','Chery%');
ADD_MODEL('Ant','Chery%');
ADD_MODEL('Arrizo 7','Chery%');
ADD_MODEL('Arrizo GX','Chery%');
ADD_MODEL('Bonus','Chery%');
ADD_MODEL('Bonus 3','Chery%');
ADD_MODEL('Crosseastar','Chery%');
ADD_MODEL('Impala','Chevrolet%');
ADD_MODEL('Camaro','Chevrolet%');
ADD_MODEL('Cobalt','Chevrolet%');
ADD_MODEL('Niva','Chevrolet%');
ADD_MODEL('Malibu','Chevrolet%');
ADD_MODEL('Impala','Chevrolet%');
ADD_MODEL('200','Chrysler%');
ADD_MODEL('300','Chrysler%');
ADD_MODEL('300C','Chrysler%');
ADD_MODEL('300M','Chrysler%');
ADD_MODEL('Crossfire','Chrysler%');
ADD_MODEL('Grand Voyager','Chrysler%');
ADD_MODEL('Berlingo','Citroen%');
ADD_MODEL('C1','Citroen%');
ADD_MODEL('C2','Citroen%');
ADD_MODEL('C3','Citroen%');
ADD_MODEL('C4','Citroen%');
ADD_MODEL('C5','Citroen%');
ADD_MODEL('C6','Citroen%');
ADD_MODEL('C7','Citroen%');
ADD_MODEL('C8','Citroen%');
ADD_MODEL('C-Crosser','Citroen%');
ADD_MODEL('C-Elysee','Citroen%');
ADD_MODEL('Avenger','DOGE%');
ADD_MODEL('Caliber','DOGE%');
ADD_MODEL('Charger','DOGE%');
ADD_MODEL('Dart','DOGE%');
ADD_MODEL('Durango','DOGE%');
ADD_MODEL('Journey','DOGE%');
ADD_MODEL('Nitro','DOGE%');
ADD_MODEL('Ram','DOGE%');
ADD_MODEL('Viper','DOGE%');
ADD_MODEL('124 Spider','FIATE%');
ADD_MODEL('500','FIATE%');
ADD_MODEL('500e','FIATE%');
ADD_MODEL('500L','FIATE%');
ADD_MODEL('500L Living','FIATE%');
ADD_MODEL('500S','FIATE%');
ADD_MODEL('500X','FIATE%');
ADD_MODEL('Aegea','FIATE%');
ADD_MODEL('Bronco','FORD%');
ADD_MODEL('C-Max','FORD%');
ADD_MODEL('Crown Victoria','FORD%');
ADD_MODEL('EcoSport','FORD%');
ADD_MODEL('Edge','FORD%');
ADD_MODEL('Escape','FORD%');
ADD_MODEL('Focus','FORD%');
ADD_MODEL('Galaxy','FORD%');
ADD_MODEL('Fiesta ST','FORD%');
ADD_MODEL('Atlas','GELLY%');
ADD_MODEL('Coolray','GELLY%');
ADD_MODEL('Emgrand','GELLY%');
ADD_MODEL('Emgrand 7','GELLY%');
ADD_MODEL('Emgrand EC7','GELLY%');
ADD_MODEL('GC6','GELLY%');
ADD_MODEL('Otaka','GELLY%');
ADD_MODEL('Tugella','GELLY%');
ADD_MODEL('Brio','HAFEI%');
ADD_MODEL('Princip','HAFEI%');
ADD_MODEL('3','HAIMA%');
ADD_MODEL('M3','HAIMA%');
ADD_MODEL('M8','HAIMA%');
ADD_MODEL('S7','HAIMA%');
ADD_MODEL('F7','HAVAL%');
ADD_MODEL('F7X','HAVAL%');
ADD_MODEL('H5','HAVAL%');
ADD_MODEL('H9','HAVAL%');
ADD_MODEL('Accord','HONDA%');
ADD_MODEL('Civic','HONDA%');
ADD_MODEL('Clarity Fuel Cell ','HONDA%');
ADD_MODEL('Crosstour','HONDA%');
ADD_MODEL('Fit','HONDA%');
ADD_MODEL('Insight','HONDA%');
ADD_MODEL('Jazz','HONDA%');
ADD_MODEL('Legend','HONDA%');
ADD_MODEL('H1','HUMMER%');
ADD_MODEL('H2','HUMMER%');
ADD_MODEL('H3','HUMMER%');
ADD_MODEL('Accent','HYUNDAI%');
ADD_MODEL('Creta','HYUNDAI%');
ADD_MODEL('Elantra','HYUNDAI%');
ADD_MODEL('Equus','HYUNDAI%');
ADD_MODEL('Genesis','HYUNDAI%');
ADD_MODEL('Genesis Coupe','HYUNDAI%');
ADD_MODEL('Genesis G70','HYUNDAI%');
ADD_MODEL('Grandeur','HYUNDAI%');
ADD_MODEL('Ioniq','HYUNDAI%');
ADD_MODEL('IX20','HYUNDAI%');
ADD_MODEL('NF Sonata','HYUNDAI%');
ADD_MODEL('Solaris','HYUNDAI%');
ADD_MODEL('FX','INFINITY%');
ADD_MODEL('JX','INFINITY%');
ADD_MODEL('Q30','INFINITY%');
ADD_MODEL('Q50','INFINITY%');
ADD_MODEL('Q60','INFINITY%');
ADD_MODEL('QX30','INFINITY%');
ADD_MODEL('QX80','INFINITY%');
ADD_MODEL('E-Pace','JAGUAR%');
ADD_MODEL('F-Pace','JAGUAR%');
ADD_MODEL('F-Type','JAGUAR%');
ADD_MODEL('I-Pace','JAGUAR%');
ADD_MODEL('XE','JAGUAR%');
ADD_MODEL('XF','JAGUAR%');
ADD_MODEL('XFR','JAGUAR%');
ADD_MODEL('XFR-S','JAGUAR%');
ADD_MODEL('Cherokee','JEEP%');
ADD_MODEL('Commander','JEEP%');
ADD_MODEL('Compass','JEEP%');
ADD_MODEL('Grand Cherokee','JEEP%');
ADD_MODEL('Grand Commander','JEEP%');
ADD_MODEL('Liberty','JEEP%');
ADD_MODEL('Renegade','JEEP%');
ADD_MODEL('Wrangler','JEEP%');
ADD_MODEL('Cadenza','KIA%');
ADD_MODEL('Carens','KIA%');
ADD_MODEL('Carnival','KIA%');
ADD_MODEL('Ceed','KIA%');
ADD_MODEL('Cerato','KIA%');
ADD_MODEL('K2 Cross','KIA%');
ADD_MODEL('K9','KIA%');
ADD_MODEL('K900','KIA%');
ADD_MODEL('Magentis','KIA%');
ADD_MODEL('Mohave','KIA%');
ADD_MODEL('Niro','KIA%');
ADD_MODEL('Opirus','KIA%');
ADD_MODEL('Optima','KIA%');
ADD_MODEL('Picanto','KIA%');
ADD_MODEL('ProCeed','KIA%');
ADD_MODEL('Quoris','KIA%');
ADD_MODEL('Rio','KIA%');
ADD_MODEL('Seltos','KIA%');
ADD_MODEL('Sorento','KIA%');
ADD_MODEL('Soul','KIA%');
ADD_MODEL('2104','LADA%');
ADD_MODEL('2107','LADA%');
ADD_MODEL('2110','LADA%');
ADD_MODEL('4x4','LADA%');
ADD_MODEL('Granta','LADA%');
ADD_MODEL('Granta Sport','LADA%');
ADD_MODEL('Kalina','LADA%');
ADD_MODEL('Kalina Cross','LADA%');
ADD_MODEL('Largus','LADA%');
ADD_MODEL('Largus Cross','LADA%');
ADD_MODEL('Priora','LADA%');
ADD_MODEL('Samara','LADA%');
ADD_MODEL('Ypsilon','LANCIA%');
ADD_MODEL('Defender 110','LAND ROVER%');
ADD_MODEL('Defender 90','LAND ROVER%');
ADD_MODEL('Discovery','LAND ROVER%');
ADD_MODEL('Discovery Sport','LAND ROVER%');
ADD_MODEL('Freelander','LAND ROVER%');
ADD_MODEL('Range Rover','LAND ROVER%');
ADD_MODEL('Range Rover Sport','LAND ROVER%');
ADD_MODEL('CT','LEXUS%');
ADD_MODEL('ES','LEXUS%');
ADD_MODEL('GS','LEXUS%');
ADD_MODEL('GS F','LEXUS%');
ADD_MODEL('GX','LEXUS%');
ADD_MODEL('LC','LEXUS%');
ADD_MODEL('LFA','LEXUS%');
ADD_MODEL('UX','LEXUS%');
ADD_MODEL('Myway','LIFAN%');
ADD_MODEL('Solano','LIFAN%');
ADD_MODEL('Aviator','LINCOLN%');
ADD_MODEL('MKC','LINCOLN%');
ADD_MODEL('Navigator','LINCOLN%');
ADD_MODEL('Ghibli','MASERATI%');
ADD_MODEL('Gran Cabrio','MASERATI%');
ADD_MODEL('Gran Turismo','MASERATI%');
ADD_MODEL('Levante','MASERATI%');
ADD_MODEL('Quattroporte','MASERATI%');
ADD_MODEL('2','MAZDA%');
ADD_MODEL('3','MAZDA%');
ADD_MODEL('5','MAZDA%');
ADD_MODEL('6','MAZDA%');
ADD_MODEL('CX-3','MAZDA%');
ADD_MODEL('CX-4','MAZDA%');
ADD_MODEL('CX-5','MAZDA%');
ADD_MODEL('CX-7','MAZDA%');
ADD_MODEL('CX-9','MAZDA%');
ADD_MODEL('RX-5','MAZDA%');
ADD_MODEL('RX-7','MAZDA%');
ADD_MODEL('RX-8','MAZDA%');
ADD_MODEL('E-Class','MERCEDES-BENZ%');
ADD_MODEL('S-Class','MERCEDES-BENZ%');
ADD_MODEL('S-Class AMG','MERCEDES-BENZ%');
ADD_MODEL('CLS-Class AMG','MERCEDES-BENZ%');
ADD_MODEL('G-Class','MERCEDES-BENZ%');
ADD_MODEL('G-Class AMG','MERCEDES-BENZ%');
ADD_MODEL('GLA-Class','MERCEDES-BENZ%');
ADD_MODEL('GLC ','MERCEDES-BENZ%');
ADD_MODEL('C-Class','MERCEDES-BENZ%');
ADD_MODEL('C-Class AMG','MERCEDES-BENZ%');
ADD_MODEL('V-Class','MERCEDES-BENZ%');
ADD_MODEL('SLC','MERCEDES-BENZ%');
ADD_MODEL('SL-Class','MERCEDES-BENZ%');
ADD_MODEL('SL-Class AMG','MERCEDES-BENZ%');
ADD_MODEL('SLK-Class','MERCEDES-BENZ%');
ADD_MODEL('SLR McLaren','MERCEDES-BENZ%');
ADD_MODEL('SLS AMG','MERCEDES-BENZ%');
ADD_MODEL('X-Class','MERCEDES-BENZ%');
ADD_MODEL('Viano','MERCEDES-BENZ%');
ADD_MODEL('ASX','MITSUBISHI%');
ADD_MODEL('Attrage','MITSUBISHI%');
ADD_MODEL('Colt','MITSUBISHI%');
ADD_MODEL('Eclipse','MITSUBISHI%');
ADD_MODEL('Eclipse Cross','MITSUBISHI%');
ADD_MODEL('Galant','MITSUBISHI%');
ADD_MODEL('Lancer Evolution','MITSUBISHI%');
ADD_MODEL('Outlander','MITSUBISHI%');
ADD_MODEL('Pajero','MITSUBISHI%');
ADD_MODEL('Space Star','MITSUBISHI%');
ADD_MODEL('Pajero Sport','MITSUBISHI%');
ADD_MODEL('350Z','NISSAN%');
ADD_MODEL('Almera','NISSAN%');
ADD_MODEL('Almera Classic','NISSAN%');
ADD_MODEL('Ariya','NISSAN%');
ADD_MODEL('Cube','NISSAN%');
ADD_MODEL('Fuga','NISSAN%');
ADD_MODEL('GT-R','NISSAN%');
ADD_MODEL('GT-R NISMO','NISSAN%');
ADD_MODEL('Note Nismo','NISSAN%');
ADD_MODEL('Patrol','NISSAN%');
ADD_MODEL('Qashqai','NISSAN%');
ADD_MODEL('ALERO','OLDSMOBILE%');
ADD_MODEL('Adam','OPEL%');
ADD_MODEL('Ampera','OPEL%');
ADD_MODEL('Astra','OPEL%');
ADD_MODEL('Cascada','OPEL%');
ADD_MODEL('Vivaro','OPEL%');
ADD_MODEL('Zafira','OPEL%');
ADD_MODEL('1007','PEOGEOT%');
ADD_MODEL('107','PEOGEOT%');
ADD_MODEL('2008','PEOGEOT%');
ADD_MODEL('3008','PEOGEOT%');
ADD_MODEL('308','PEOGEOT%');
ADD_MODEL('5008','PEOGEOT%');
ADD_MODEL('718 Boxster','PORSCHE%');
ADD_MODEL('718 Cayman','PORSCHE%');
ADD_MODEL('911 Carrera','PORSCHE%');
ADD_MODEL('911 Carrera Cabriolet','PORSCHE%');
ADD_MODEL('911 GT2 RS','PORSCHE%');
ADD_MODEL('911 GT3','PORSCHE%');
ADD_MODEL('Matiz','RAVON%');
--ADD_MODEL('RENAULT%');
--ADD_MODEL('ROVER');
--ADD_MODEL('SAAB');
--ADD_MODEL('SAIPA');
--ADD_MODEL('SANTANA');
--ADD_MODEL('SEAT');
--ADD_MODEL('SKODA');
--ADD_MODEL('SMART');
--ADD_MODEL('SUBARU');
--ADD_MODEL('SUZUKI');
--ADD_MODEL('TATA');
--ADD_MODEL('TESLA');
--ADD_MODEL('TOYOTA');
--ADD_MODEL('VOLKSWAGEN');
--ADD_MODEL('VOLVO');
--ADD_MODEL('VORTEX');
--ADD_MODEL('√¿«');
--ADD_MODEL('«¿«');
--ADD_MODEL('ÃŒ— ¬»◊');
--ADD_MODEL('”¿«');
--ADD_MODEL('› — Àﬁ«»¬');
END;
SELECT* FROM MODEL_;
DECLARE
BEGIN
FOR NP IN 11..10000
LOOP
ADD_USER(NP,NP,NP);
END LOOP;
END;
SELECT * FROM USERS_;
set serveroutput on format wraped;
BEGIN USER_BY_ID(1100);END;